AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # CodeUriはpackaje.jsonが格納されたディレクトリを指定する必要がある
      CodeUri: hello-world/
      # 関数実行時に呼び出すべきエントリポイント、dot以降は実際の関数名と整合させること
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        # バンドル処理を開始する際の「元となるソースファイル」を指定
        EntryPoints: 
        - app.ts

  HelloWorldFunction2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # CodeUriはpackaje.jsonが格納されたディレクトリを指定する必要がある
      CodeUri: hello-world/
      # 関数実行時に呼び出すべきエントリポイント、dot以降は実際の関数名と整合させること
      Handler: app2.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        # バンドル処理を開始する際の「元となるソースファイル」を指定
        EntryPoints: 
        - app2.ts
